apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: grafana
name: grafana
releaseName: grafana
version: 8.4.6
repo: https://grafana.github.io/helm-charts
valuesInline:
  ingress:
    enabled: false
  service:
    enabled: false