apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb

resources:
  - namespace.yaml
  - metallb-ipAddressPool.yaml
  - metallb-l2Advertisement.yaml

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: 0.14.9
    releaseName: metallb
