---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
    providers:
      longhorn:
        url: http://longhorn-frontend.longhorn.svc.cluster.local
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Links:
        - Github:
            - abbr: GH
              href: https://github.com/bensonphillipsiv?tab=repositories
        - ChatGPT:
            - abbr: GPT
              href: https://chat.openai.com
  services.yaml: |
    - Services:
        - Home Assistant:
            href: https://ha.bensonphillips.dev
            ping: https://ha.bensonphillips.dev
            icon: home-assistant-alt
        - Node Red:
            href: http://node-red.bensonphillips.dev
            ping: http://node-red.bensonphillips.dev
            icon: node-red
        - ESP Home:
            href: https://esphome.bensonphillips.dev
            ping: esphome.esphome.svc.cluster.local
            icon: esphome
        - MQTT:
            href: http://mqtt.bensonphillips.dev
            siteMonitor: mqtt-emqx-headless.mqtt.svc.cluster.local
            icon: emqx
    - Mangement:
        - Argo CD:
            href: http://argocd.bensonphillips.dev
            siteMonitor: https://argocd-server.argocd.svc.cluster.local
            icon: argo-cd
            widget:
              type: argocd
              url: https://argocd-server.argocd.svc.cluster.local
        - Longhorn:
            href: http://longhorn.bensonphillips.dev
            siteMonitor: http://longhorn-frontend.longhorn.svc.cluster.local
            icon: longhorn
    - Monitoring:
        - Grafana:
            href: http://grafana.bensonphillips.dev
            siteMonitor: http://grafana.grafana.svc.cluster.local
            icon: grafana
            widget:
              type: grafana
              url: http://grafana.grafana.svc.cluster.local
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - longhorn:
        expanded: true
        total: true
        labels: true
        nodes: true
  docker.yaml: ""
---
