apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: default
  sources:
    - chart: homepage
      repoURL: 'https://jameswynn.github.io/helm-charts'
    - repoURL: 'https://github.com/bensonphillipsiv/home-infra'
      path: apps/homepage/resources
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: homepage
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
