apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: ingress-nginx
name: ingress-nginx
releaseName: ingress-nginx
version: 4.10.1
repo: https://kubernetes.github.io/ingress-nginx
valuesFile: values.yaml