apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: shared-secrets-store
  namespace: external-secrets
spec:
  provider:
    kubernetes:
      remoteNamespace: external-secrets
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: external-secrets
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: doppler-auth-api
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token
            namespace: external-secrets
            key: DOPPLER_TOKEN
---