apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - clusterSecretStore.yaml

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.17.0
    releaseName: external-secrets
    valuesInLine:
      certController:
        create: false
      webhook:
        create: false