apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - chart: cert-manager
      repoURL: 'https://charts.jetstack.io'
      targetRevision: 1.14.5
      helm:
        parameters:
        - name: installCRDs
          value: 'true'
    - repoURL: 'https://github.com/bensonphillipsiv/home-infra'
      path: apps/cert-manager/resources
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
