---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: benson.phillipsiv@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          cloudflare:
            email: benson.phillipsiv@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-key
              key: CLOUDFLARE_API_KEY
---
