apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: shared-secrets-store
  target:
    name: cloudflare-api-key
  data:
  - secretKey: cloudflare-api-key
    remoteRef:
      key: shared-secrets
      property: cloudflare-api-key