---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: cloudflare-api-key
  data:
    - secretKey: CLOUDFLARE_API_KEY
      remoteRef:
        key: CLOUDFLARE_API_KEY
---
