apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: cert-manager
name: cert-manager
releaseName: cert-manager
version: 1.14.5
repo: https://charts.jetstack.io
valuesInline:
  installCRDs: true
  namespace: kube-system
  extraArgs:
    - --enable-certificate-owner-ref=true
    - --dns01-recursive-nameservers-only
    - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
