apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: cert-manager
name: cert-manager
releaseName: cert-manager
version: 1.14.5
repo: https://charts.jetstack.io
valuesInline:
  installCRDs: true
