apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: longhorn
name: longhorn
releaseName: longhorn
version: 1.6.2
repo: https://charts.longhorn.io
valuesInline:
  service:
    ui:
      type: ClusterIP
      nodePort: null
      clusterIP: None
    manager:
      type: ClusterIP
      nodePort: ""
      loadBalancerIP: ""
      loadBalancerSourceRanges: ""

  persistence:
    defaultClassReplicaCount: 3

  longhornUI:
    replicas: 1