service:
  ui:
    type: ClusterIP
    nodePort: null
    ClusterIP: None
  manager:
    type: ClusterIP
    nodePort: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: ""

persistence:
  defaultClassReplicaCount: 3

longhornUI:
  replicas: 1