apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: node-red

resources:
  - ingress.yaml

helmCharts:
  - name: node-red
    repo: https://schwarzit.github.io/node-red-chart
    version: 0.34.0
    releaseName: node-red
    valuesInline:
      persistence:
        enabled: true
        size: 1Gi

patches:
  - path: loadBalancer.yaml

# patchesJson6902:
#   - target:
#       group: ""
#       version: v1
#       kind: Service
#       name: node-red
#     path: patch-node-red-service.json