apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-red
  namespace: argocd
spec:
  project: default
  source:
    chart: node-red
    repoURL: 'https://schwarzit.github.io/node-red-chart/'
    targetRevision: 0.29.0
    helm:
      values: |
        persistence:
          enabled: true
          size: 1Gi
        ingress:
          enabled: true
          className: nginx
          hosts: 
            - host: node-red.local
              paths:
                - path: /
                  pathType: Prefix
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: node-red
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true