apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-red
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: 'https://schwarzit.github.io/node-red-chart/'
    targetRevision: 0.29.0
    server: 'https://kubernetes.default.svc'
    namespace: node-red
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
