apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-red
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/bensonphillipsiv/home-infra'
      path: apps/node-red/resources
      kustomize:
        commonLabels: {
          app.kubernetes.io/name: node-red,
          app: node-red
        }
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: node-red
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true