---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: esphome
  name: esphome
spec:
  type: ClusterIP
  ports:
  - port: 6052
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: esphome  