---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-longhorn-s3-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: aws-longhorn-s3-key
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: AWS_LONGHORN_S3_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: AWS_LONGHORN_S3_KEY
---
