apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: postgres
name: postgresql
releaseName: postgresql
version: 15.5.26
repo: https://charts.bitnami.com/bitnami
valuesInline:
  auth:
    enablePostgresUser: false
    existingSecret: postgres-config
    replicationUsername: null

    secretKeys:
      adminPasswordKey: POSTGRES_PASSWORD
      replicationPasswordKey: null
      userPasswordKey: null

  primary:
    service:
      loadBalancerIP: 192.168.1.198
      type: LoadBalancer