apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - metallb-IpAddressPool.yaml
  - metallb-L2Advertisement.yaml

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: 0.14.9
    releaseName: metallb
    valuesInline:
      commonLabels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
