apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  sources:
    - chart: ingress-nginx
      repoURL: 'https://kubernetes.github.io/ingress-nginx'
      targetRevision: 4.9.0
      helm:
        valueFiles:
          - $values/apps/nginx/values.yaml
    - repoURL: 'https://github.com/bensonphillipsiv/home-infra'
      ref: values
    - repoURL: 'https://github.com/bensonphillipsiv/home-infra'
      path: apps/longhorn/resources
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
