apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-assistant

resources:
  - deployment.yaml
  - ingress.yaml
  - pvc.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: home-assistant
  app: home-assistant