apiVersion: v1
kind: Service
metadata:
  name: longhorn
spec:
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
