apiVersion: v1
kind: Service
metadata:
  name: longhorn
  labels:
    app.kubernetes.io/name: longhorn-frontend
spec:
  selector:
    app.kubernetes.io/name: longhorn-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
