apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-red
  namespace: node-red
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
      - configmaps
      - services
    verbs:
      - get
      - list
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-red
  namespace: node-red
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: node-red
subjects:
  - kind: ServiceAccount
    name: node-red
    namespace: node-red
