apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
   background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Links:
        - Github:
            - abbr: GH
              href: https://github.com/bensonphillipsiv?tab=repositories
  services.yaml: |

    - Hardware:
        - Beelink:
            href: http://192.168.1.100
            ping: http://192.168.1.100
            icon: proxmox
        - Raspberry Pi 1:
            href: http://192.168.1.101
            ping: http://192.168.1.101
            icon: raspberrypi
        - Raspberry Pi 2:
            href: http://192.168.1.102
            ping: http://192.168.1.102
            icon: raspberrypi
        - Router:
            href: http://192.168.1.1
            ping: http://192.168.1.1
            icon: watchyourlan
    - Services:
        - Home Assistant:
            href: https://homeassistant.bensonphillips.dev
            ping: http://home-assistant.homeassistant.svc.cluster.local
            icon: home-assistant-alt
        - ESP Home:
            href: https://esphome.bensonphillips.dev
            ping: http://esphome.esphome.svc.cluster.local
            icon: esphome
        - Node Red:
            href: http://node-red.bensonphillips.dev
            ping: http://node-red.node-red.svc.cluster.local
            icon: node-red
    - Mangement:
        - Argo CD:
            href: http://argocd.bensonphillips.dev
            ping: http://argocd.bensonphillips.dev:8080
            icon: argocd
        - Longhorn:
            href: http://longhorn.bensonphillips.dev
            ping: http://longhorn-frontend.longhorn.svc.cluster.local
            icon: longhorn
    - Monitoring:
        - Grafana:
            href: http://grafana.bensonphillips.dev
            ping: http://grafana.monitoring.svc.cluster.local
            icon: grafana

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
  docker.yaml: ""