apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
   background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
   providers:
    longhorn:
      url: https://longhorn.bensonphillips.dev
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Links:
        - Github:
            - abbr: GH
              href: https://github.com/bensonphillipsiv?tab=repositories
        - ChatGPT:
            - abbr: GPT
              href: https://chat.openai.com
  services.yaml: |

    - Hardware:
        - Beelink:
            href: http://192.168.1.100:8006
            ping: http://192.168.1.100:8006
            icon: proxmox
            widget:
              type: proxmox
              url: https://192.168.1.100:8006
              username: api@pam!homepage
              password: 542e0903-ed06-4ec0-a1d4-a0156f4b07bb
        - Raspberry Pi 1:
            href: http://192.168.1.131
            ping: http://192.168.1.131
            icon: raspberrypi
        - Raspberry Pi 2:
            href: http://192.168.1.132
            ping: http://192.168.1.132
            icon: raspberrypi
        - Router:
            href: http://192.168.1.1
            ping: http://192.168.1.1
            icon: watchyourlan
    - Services:
        - Home Assistant:
            href: https://homeassistant.bensonphillips.dev
            ping: http://home-assistant.homeassistant.svc.cluster.local
            icon: home-assistant-alt
        - Node Red:
            href: http://node-red.bensonphillips.dev
            ping: http://node-red.node-red.svc.cluster.local
            icon: node-red
        - ESP Home:
            href: https://esphome.bensonphillips.dev
            ping: http://esphome.esphome.svc.cluster.local
            icon: esphome
        - MQTT:
            href: http://mqtt.bensonphillips.dev
            ping: http://mqtt-emqx-headless.mqtt.svc.cluster.local
            icon: emqx
    - Mangement:
        - Argo CD:
            href: http://argocd.bensonphillips.dev
            ping: http://argocd-server.argocd.svc.cluster.local
            icon: argocd
        - Longhorn:
            href: http://longhorn.bensonphillips.dev
            ping: http://longhorn-frontend.longhorn.svc.cluster.local
            icon: longhorn
    - Monitoring:
        - Grafana:
            href: http://grafana.bensonphillips.dev
            ping: http://grafana.monitoring.svc.cluster.local
            icon: grafana
            widget:
              type: grafana
              url: https://grafana.bensonphillips.dev
              username: admin
              password: password

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - longhorn:
        expanded: true
        # Shows a node representing the aggregate values
        total: true
        # Shows the node names as labels
        labels: true
        # Show the nodes
        nodes: true
  docker.yaml: ""