apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

resources:

helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 16.7.4
    releaseName: postgresql
    valuesInline:
      auth:
        enablePostgresUser: true
        postgresPassword: ""
      primary:
        service:
          type: LoadBalancer
          loadBalancerIP: 192.168.1.104
        pgHbaConfiguration: |
          local all all trust
          host all all 0.0.0.0/0 trust
          host all all ::/0 trust