apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/bensonphillipsiv/home-infra'
      path: apps/postgres/resources
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: postgres
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true