apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  sources:
    - chart: postgres
      repoURL: 'registry-1.docker.io/bitnamicharts/postgresql'
      targetRevision: 15.5.26
      helm:
        valueFiles:
        - $values/apps/postgres/values.yaml
    - repoURL: 'https://github.com/bensonphillipsiv/home-infra'
      ref: values
    # - repoURL: 'https://github.com/bensonphillipsiv/home-infra'
    #   path: apps/postgres/resources
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: postgres
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true