apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  sources:
    - chart: pihole
      repoURL: 'https://mojo2600.github.io/pihole-kubernetes/'
      targetRevision: 2.20.0
      helm:
        valueFiles:
        - $values/apps/pihole/values.yaml
    - repoURL: 'https://github.com/bensonphillipsiv/home-infra'
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pihole
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true