kind: ConfigMap
apiVersion: v1
metadata:
  name: home-assistant-configmap
data:
  configuration.yaml: |
    default_config:
    frontend:
      themes: !include_dir_merge_named themes
    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 192.168.1.0/24
        - 172.20.0.0/24
        - 10.42.0.0/16