kind: ConfigMap
apiVersion: v1
metadata:
  name: home-assistant
data:
  configuration.yaml: |-
    default_config:
    frontend:
      themes: !include_dir_merge_named themes
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 192.168.1.0/24
        - 172.20.0.0/24
        - 10.42.0.0/16
    panel_iframe:
      nodered:
        title: Node-RED
        icon: mdi:lan
        url: https://node-red.bensonphillips.dev
        require_admin: true
      esphome:
        title: ESP-Home
        icon: mdi:chip
        url: https://esphome.bensonphillips.dev
        require_admin: true