apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/bensonphillipsiv/home-infra'
      path: apps/homeassistant/resources
      directory:
        include: '{kustomization.yaml}'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: homeassistant
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
