apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/bensonphillipsiv/home-infra'
      path: apps/homeassistant/resources
      kustomize:
        commonLabels: {
          app.kubernetes.io/name: home-assistant,
          app: home-assistant
        }
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: homeassistant
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
