apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
  - pvc.yaml
  - service.yaml
  - rb.yaml
  - role.yaml
  - serviceaccount.yaml