apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-red
  namespace: node-red
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
      - configmaps
      - services
    verbs:
      - get
      - list
      - watch