apiVersion: v1
kind: Secret
metadata:
  name: longhorn
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
type: Opaque