apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: esphome
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/bensonphillipsiv/home-infra'
      path: apps/esphome/resources
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: esphome
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
