apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    - chart: grafana
      repoURL: 'https://grafana.github.io/helm-charts'
      targetRevision: 7.0.19
    - repoURL: 'https://github.com/bensonphillipsiv/home-infra'
      path: apps/esphome/resources
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
