apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 7.0.19
    helm:
      values: |
        persistence:
          enabled: true
          size: 1Gi
        values: |
        ingress:
          enabled: true
          annotations: {
            kubernetes.io/ingress.class: "nginx",
            ingress.kubernetes.io/rewrite-target: /
          }
          hosts: 
            - grafana.local
          ingressClassName: 'nginx'
          path: /
          pathType: Prefix
          extraPaths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: grafana
                  port:
                    number: 80
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
