apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    - chart: grafana
      repoURL: 'https://grafana.github.io/helm-charts'
      targetRevision: 8.4.6
    - repoURL: 'https://github.com/bensonphillipsiv/home-infra'
      path: apps/grafana/resources
    #   helm:
    #     valueFiles:
    #     - $values/apps/grafana/values.yaml
    # - repoURL: 'https://github.com/bensonphillipsiv/home-infra'
    #   ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    # automated:
    #   prune: true
    #   selfHeal: true
