apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
  - ingress.yaml

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 9.2.0
    releaseName: grafana
    valuesInline:
      grafana.ini:
        auth:
          disable_login_form: false          # hide the login screen  :contentReference[oaicite:0]{index=0}
        auth.anonymous:
          enabled: true
          org_role: Admin