apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 9.2.0
    releaseName: grafana