apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  labels:
    app: argocd
spec:
  type: clusterIP
  # clusterIP: None
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: argocd-server