apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: "argocd"
  labels:
    app.kubernetes.io/instance: "argocd-release"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/name: "argocd"
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8080
    appProtocol: http
  selector:
    app.kubernetes.io/instance: "argocd-release"