apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    chart: prometheus
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 25.8.2
    helm:
      values: |
        server:
          ingress:
            enabled: true
            annotations: {
              kubernetes.io/ingress.class: "nginx"
              ingress.kubernetes.io/rewrite-target: /
            }
            hosts: 
              - prometheus.local
            ingressClassName: 'nginx-system'
            path: /
            pathType: Prefix
            extraPaths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: prometheus-server
                    port:
                      number: 80
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prometheus
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
