apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - chart: prometheus
      repoURL: 'https://prometheus-community.github.io/helm-charts'
      targetRevision: 25.8.2
      helm:
        valueFiles:
        - $values/apps/prometheus/values.yaml
    - repoURL: 'https://github.com/bensonphillipsiv/home-infra'
      ref: values
    - repoURL: 'https://github.com/bensonphillipsiv/home-infra'
      path: apps/prometheus/resources
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prometheus
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
