apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: common-appset
spec:
  generators:
    - git:
        repoURL: https://github.com/bensonphillipsiv/home-infra
        revision: revamp
        directories:
          - path: "apps/*"
  template:
    metadata:
      name: "{{path[1]}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/bensonphillipsiv/home-infra
        targetRevision: revamp
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true