apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mqtt

resources:

helmCharts:
  - name: emqx
    repo: https://repos.emqx.io/charts
    version: 5.8.6
    releaseName: mqtt-emqx
    valuesInline:
      replicaCount: 1
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.111
