apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mqtt
  namespace: argocd
spec:
  project: default
  sources:
    - chart: emqx
      repoURL: 'https://repos.emqx.io/charts'
      targetRevision: 5.4.1
      helm:
        valueFiles:
        - $values/apps/mqtt/values.yaml
    - repoURL: 'https://github.com/bensonphillipsiv/home-infra'
      ref: values
    # - repoURL: 'https://github.com/bensonphillipsiv/home-infra'
    #   path: apps/longhorn/resources
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mqtt
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
