apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mqtt-emqx
  namespace: mqtt
spec:
  template:
    spec:
      containers:
        - name: emqx
          env:
            - name: EMQX_HOST
              value: "$(POD_NAME).mqtt-emqx-headless.mqtt.svc.cluster.local"